// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGNo-B5AM0PmOP9kuRhGx307TYJWLzFpI',
    appId: '1:621696723030:web:c52fe3fc8b4192e030b3f7',
    messagingSenderId: '621696723030',
    projectId: 'book-da589',
    authDomain: 'book-da589.firebaseapp.com',
    storageBucket: 'book-da589.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWgAMgD5Ev0qIK6Fzym5z6PH6TIes8ilU',
    appId: '1:621696723030:android:680da511e0d4f79230b3f7',
    messagingSenderId: '621696723030',
    projectId: 'book-da589',
    storageBucket: 'book-da589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD14xU6jT07F8rcbmvWUyFnzsHJn4bMFGM',
    appId: '1:621696723030:ios:b7ef1c0c263edaea30b3f7',
    messagingSenderId: '621696723030',
    projectId: 'book-da589',
    storageBucket: 'book-da589.appspot.com',
    iosBundleId: 'com.example.bookstoreMadProject',
  );
}
